project(LogFileWatch):aceexe{
 	exename = LogFileWatch

 Source_Files{
  ./*.cpp
  ./TinyXML/*.cpp
 }
 includes += ./ ./TinyXML
 macros += __LINUX__
 
 exeout = ../../../purenessscopeserver/PurenessScopeServer/Linux_Bin
}