project(PacketParse_Interface_Http):acelib{
  sharedname=PacketParse_Interface_Http
  dynamicflags += PACKETPARSE_INTERFACE_HTTP_EXPORTS

  Source_Files{ 
  ./*.cpp
  }
  
  specific (prop:microsoft){
  dllout = ../FrameCore/Windows_Bin
  } else {
  macros += __LINUX__
  dllout = ../FrameCore/Linux_Bin
  } 
  includes += ../Common
}