##
## Auto Generated makefile by CodeLite IDE
## any manual changes will be erased      
##
## Release
ProjectName            :=XML2CPP
ConfigurationName      :=Release
WorkspacePath          :=../../Build/Linux
ProjectPath            :=../PluginMaker/XML2CPP
IntermediateDirectory  :=$(WorkspacePath)/Temp
OutDir                 := $(IntermediateDirectory)
CurrentFileName        :=
CurrentFilePath        :=
CurrentFileFullPath    :=
User                   :=fox mulder
Date                   :=2019年03月30日
CodeLitePath           :=/home/fox-mulder/.codelite
LinkerName             :=/usr/bin/g++
SharedObjectLinkerName :=/usr/bin/g++ -shared -fPIC
ObjectSuffix           :=.o
DependSuffix           :=.o.d
PreprocessSuffix       :=.i
DebugSwitch            :=-g 
IncludeSwitch          :=-I
LibrarySwitch          :=-l
OutputSwitch           :=-o 
LibraryPathSwitch      :=-L
PreprocessorSwitch     :=-D
SourceSwitch           :=-c 
OutputFile             :=$(WorkspacePath)/Linux_Bin/$(ProjectName)
Preprocessors          :=
ObjectSwitch           :=-o 
ArchiveOutputSwitch    := 
PreprocessOnlySwitch   :=-E
ObjectsFileList        :="XML2CPP.txt"
PCHCompileFlags        :=
MakeDirCommand         :=mkdir -p
LinkOptions            :=  -O0
IncludePath            :=  $(IncludeSwitch). $(IncludeSwitch)../../ThirdLib/include/TinyXML $(IncludeSwitch)../../ThirdLib/include $(IncludeSwitch)../../ThirdLib/thirdparty $(IncludeSwitch)../../ThirdLib/src 
IncludePCH             := 
RcIncludePath          := 
Libs                   := 
ArLibs                 :=  
LibPath                := $(LibraryPathSwitch). $(LibraryPathSwitch). $(LibraryPathSwitch)Release 

##
## Common variables
## AR, CXX, CC, AS, CXXFLAGS and CFLAGS can be overriden using an environment variables
##
AR       := /usr/bin/ar rcu
CXX      := /usr/bin/g++
CC       := /usr/bin/gcc
CXXFLAGS :=  -g -Wall $(Preprocessors)
CFLAGS   :=   $(Preprocessors)
ASFLAGS  := 
AS       := /usr/bin/as


##
## User defined environment variables
##
CodeLiteDir:=/usr/share/codelite
Objects0=$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(ObjectSuffix) $(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(ObjectSuffix) $(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(ObjectSuffix) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(ObjectSuffix) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(ObjectSuffix) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(ObjectSuffix) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(ObjectSuffix) 



Objects=$(Objects0) 

##
## Main Build Targets 
##
.PHONY: all clean PreBuild PrePreBuild PostBuild MakeIntermediateDirs
all: $(OutputFile)

$(OutputFile): $(IntermediateDirectory)/.d $(Objects) 
	@$(MakeDirCommand) $(@D)
	@echo "" > $(IntermediateDirectory)/.d
	@echo $(Objects0)  > $(ObjectsFileList)
	$(LinkerName) $(OutputSwitch)$(OutputFile) @$(ObjectsFileList) $(LibPath) $(Libs) $(LinkOptions)

MakeIntermediateDirs:
	@test -d $(WorkspacePath)/Temp || $(MakeDirCommand) $(WorkspacePath)/Temp


$(IntermediateDirectory)/.d:
	@test -d $(WorkspacePath)/Temp || $(MakeDirCommand) $(WorkspacePath)/Temp

PreBuild:


##
## Objects
##
$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(ObjectSuffix): ./XML2CPP/ParseCAPIFile.cpp $(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "./XML2CPP/ParseCAPIFile.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(DependSuffix): ./XML2CPP/ParseCAPIFile.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(DependSuffix) -MM ./XML2CPP/ParseCAPIFile.cpp

$(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(PreprocessSuffix): ./XML2CPP/ParseCAPIFile.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/XML2CPP_ParseCAPIFile.cpp$(PreprocessSuffix) ./XML2CPP/ParseCAPIFile.cpp

$(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(ObjectSuffix): ./XML2CPP/XML2CPP.cpp $(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "./XML2CPP/XML2CPP.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(DependSuffix): ./XML2CPP/XML2CPP.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(DependSuffix) -MM ./XML2CPP/XML2CPP.cpp

$(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(PreprocessSuffix): ./XML2CPP/XML2CPP.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/XML2CPP_XML2CPP.cpp$(PreprocessSuffix) ./XML2CPP/XML2CPP.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(ObjectSuffix): ../../ThirdLib/include/XmlOpeation.cpp $(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "../../ThirdLib/include/XmlOpeation.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(DependSuffix): ../../ThirdLib/include/XmlOpeation.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(DependSuffix) -MM ../../ThirdLib/include/XmlOpeation.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(PreprocessSuffix): ../../ThirdLib/include/XmlOpeation.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/up_up_ThirdLib_include_XmlOpeation.cpp$(PreprocessSuffix) ../../ThirdLib/include/XmlOpeation.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(ObjectSuffix): ../../ThirdLib/include/TinyXML/tinyxml.cpp $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "../../ThirdLib/include/TinyXML/tinyxml.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(DependSuffix): ../../ThirdLib/include/TinyXML/tinyxml.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(DependSuffix) -MM ../../ThirdLib/include/TinyXML/tinyxml.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(PreprocessSuffix): ../../ThirdLib/include/TinyXML/tinyxml.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxml.cpp$(PreprocessSuffix) ../../ThirdLib/include/TinyXML/tinyxml.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(ObjectSuffix): ../../ThirdLib/include/TinyXML/tinyxmlparser.cpp $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "../../ThirdLib/include/TinyXML/tinyxmlparser.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(DependSuffix): ../../ThirdLib/include/TinyXML/tinyxmlparser.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(DependSuffix) -MM ../../ThirdLib/include/TinyXML/tinyxmlparser.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(PreprocessSuffix): ../../ThirdLib/include/TinyXML/tinyxmlparser.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlparser.cpp$(PreprocessSuffix) ../../ThirdLib/include/TinyXML/tinyxmlparser.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(ObjectSuffix): ../../ThirdLib/include/TinyXML/tinyxmlerror.cpp $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "../../ThirdLib/include/TinyXML/tinyxmlerror.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(DependSuffix): ../../ThirdLib/include/TinyXML/tinyxmlerror.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(DependSuffix) -MM ../../ThirdLib/include/TinyXML/tinyxmlerror.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(PreprocessSuffix): ../../ThirdLib/include/TinyXML/tinyxmlerror.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinyxmlerror.cpp$(PreprocessSuffix) ../../ThirdLib/include/TinyXML/tinyxmlerror.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(ObjectSuffix): ../../ThirdLib/include/TinyXML/tinystr.cpp $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(DependSuffix)
	$(CXX) $(IncludePCH) $(SourceSwitch) "../../ThirdLib/include/TinyXML/tinystr.cpp" $(CXXFLAGS) $(ObjectSwitch)$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(DependSuffix): ../../ThirdLib/include/TinyXML/tinystr.cpp
	@$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(ObjectSuffix) -MF$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(DependSuffix) -MM ../../ThirdLib/include/TinyXML/tinystr.cpp

$(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(PreprocessSuffix): ../../ThirdLib/include/TinyXML/tinystr.cpp
	$(CXX) $(CXXFLAGS) $(IncludePCH) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/up_up_ThirdLib_include_TinyXML_tinystr.cpp$(PreprocessSuffix) ../../ThirdLib/include/TinyXML/tinystr.cpp


-include $(IntermediateDirectory)/*$(DependSuffix)
##
## Clean
##
clean:
	$(RM) -r $(WorkspacePath)/Temp/


