project(PacketParse_VS2015_Http):acelib{
  sharedname=PacketParse_VS2015_Http
  dynamicflags += PACKETPARSE_INTERFACE_HTTP_EXPORTS

  Source_Files{ 
  ./*.cpp
  }
  
  specific (prop:microsoft){
  dllout = ../PurenessScopeServer/Windows_Bin
  } else {
  macros += __LINUX__
  dllout = ../PurenessScopeServer/Linux_Bin
  } 
  includes += ../Common
}